# Generated by Django 5.1.4 on 2025-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='current_value',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='is_active',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
