# Generated by Django 5.1.4 on 2025-01-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
