# Generated by Django 5.1.4 on 2025-01-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='listing/images'),
        ),
    ]
