# Generated by Django 5.1.4 on 2025-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/listing/images'),
        ),
    ]
