# Generated by Django 5.1.4 on 2025-02-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='listing/images'),
        ),
    ]
